include:
  - board: nice_nano
    shield: corne_hw_left
    cmake-args: -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE
  - board: nice_nano
    shield: corne_hw_right
    cmake-args: -DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE
