CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Цей блок вирішує проблему на нових версіях ZMK
# Ми кажемо системі: "Так, у нас є USB, але ми ним не користуємось"
CONFIG_ZMK_USB=y
# Але при цьому вимикаємо його ініціалізацію при старті, щоб не було конфліктів
CONFIG_ZMK_USB_INIT=n