CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Вимикаємо стек USB повністю.
# Це прибере помилку лінкера і попередження "assigned n but got y".
CONFIG_USB_DEVICE_STACK=n

# Для певності вимикаємо консоль (вона теж може хотіти USB)
CONFIG_SERIAL=n
CONFIG_CONSOLE=n