CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Right half shouldn't use USB / BT for wired split peripheral
CONFIG_ZMK_USB=n
CONFIG_BT=n

# UART/Serial must be enabled, otherwise DEVICE_DT_GET() fails
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
