manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: zephyr-3.5  # <--- ПРАВИЛЬНА НАЗВА СТАБІЛЬНОЇ ГІЛКИ
      import: app/west.yml
  self:
    path: config